<?php

namespace UserBundle\Repository;

/**
 * NotificationTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
