<?php

namespace UserBundle\Repository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $keyword
     * @param bool   $findAll
     *
     * @return array
     */
    public function findByName(string $keyword, bool $findAll = false)
    {
        $qb = $this->createQueryBuilder('t')
            ->orWhere('t.name LIKE :keyword', 't.tag LIKE :keyword')
            ->setParameter('keyword', '%'.$keyword.'%')
        ;

        if (false === $findAll) {
            $qb
                ->andWhere('t.activated = :activated')->setParameter('activated', true)
                ->andWhere('t.deleted = :deleted')->setParameter('deleted', false)
                ->setMaxResults(8)
            ;
        }

        $qb->orderBy('t.id', 'DESC');

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
    /**
     * @param string $keyword
     *
     * @return array
     */
    public function search(string $keyword)
    {
        return $this->createQueryBuilder('t')
            ->orWhere('t.name LIKE :keyword', 't.tag LIKE :keyword')
            ->setParameter('keyword', '%'.$keyword.'%')
            ->orderBy('t.id', 'DESC')
            ->getQuery()
            ->getResult()
        ;
    }
}
