<?php

namespace UserBundle\Repository;

use UserBundle\Entity\User;

/**
 * TeamMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamMemberRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     *
     * @return array
     */
    public function findRegisterable(User $user)
    {
        return $this->createQueryBuilder('tm')
            ->join('tm.team', 'team')
            ->where('tm.user = :user')
            ->andWhere('tm.requested = :requested')
            ->andWhere('team.activated = :activated')
            ->andWhere('team.deleted = :deleted')
            ->setParameter('user', $user)
            ->setParameter('requested', false)
            ->setParameter('activated', true)
            ->setParameter('deleted', false)
            ->getQuery()
            ->getResult()
        ;
    }
}
