<?php

namespace TournamentBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;
use TournamentBundle\Entity\Battle;
use TournamentBundle\Entity\Participant;
use TournamentBundle\Entity\Tournament;

/**
 * BattleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Tournament $tournament
     *
     * @return array
     */
    public function findEndedBattlesForTournament(Tournament $tournament)
    {
        return $this->createQueryBuilder('b')
            ->where('b.tournament = :tournament')
            ->andWhere('b.endAt IS NOT NULL')
            ->setParameter('tournament', $tournament)
            ->getQuery()
            ->getResult()
        ;
    }
}
