<?php

namespace TournamentBundle\Repository;

/**
 * RankingLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingLevelRepository extends \Doctrine\ORM\EntityRepository
{
}
